Repository preservim/tagbar, pull requests merged in 2020-01, with the labels that each got.

#579 Add g:tagbar_show_balloon option
  autoload/tagbar.vim
  doc/tagbar.txt
  plugin/tagbar.vim
Labels: feature

#581 feat(dart_ctags): support for dart if dart_ctags is installed
  autoload/tagbar.vim
Labels: feature, language-support

#583 gotags: kinds support ```e:embedded``` and ```w:fields```
  autoload/tagbar.vim
Labels: language-support

#587 Fix document syntax highlight
  doc/tagbar.txt
Labels: documentation

#308 Additional function for displaying type of a current tag.
  autoload/tagbar.vim
  doc/tagbar.txt
Labels: feature
